# language: es

Característica: Resolver reto X
  Con código C
  Del sitio Y
  De la categoría Z
  Con mi usuario U

  Antecedentes:
    Dado estoy registrado en el sitio X
    Y tengo el sistema operativo A versión B
    Y he instalado el software C versión D
    Y tengo acceso a internet
    Y he resuelto el reto X-1
    Y referenciandome en la solución H

  Escenario: Primer intento fallido
    Dado estoy uenticado con mi usuario U
    Cuando ...
    Y ...
    Y ...
    Entonces el reto no es resuelto 
    Pero concluyo que ...

  Escenario: Último intento fallido
    Dado ............
    Cuando ...
    Y ...
    Y ...
    Entonces el reto no es resuelto 
    Pero concluyo que ...

  Escenario: Solución exitosa
    Dado ...
    Cuando ...
    Y ...
    Y ...
    Entonces el reto es resuelto
