# language: es

Característica: resolver reto 4
  Sin utilización de código
  Del sitio ChallengeLand
  De la categoría Steganography
  Con mi usuario Goso_Gos

Antecedentes: Implementación de herramientas
  Dado(/^que estoy Registrado en el sitio ChallengeLand$/) do
    pending # Write code here
  end
  Y tengo el sistema operativo Ubuntu 14.4
  Y he instalado el software foremost versión 1.5.7
  Y he instalado el software 010Editor versión 4.0
  Y tengo acceso a internet

Escenario: Primer intento fallido
  Dado que estoy autenticado con mi usuario U
  Cuando ...
  Y ...
  Y ...
  Entonces no resuelvo el reto
  Pero concluyo que ...

  Escenario: Último intento fallido
    Dado ...
    Cuando ...
    Y ...
    Y ...
    Entonces no resuelvo el reto
    Pero concluyo que ...

  Escenario: Solución exitosa
    Dado ...
    Cuando ...
    Y ...
    Y ...
    Entonces resuelvo el reto
